name: barista_planet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  image_picker: ^0.8.4+4
  http: ^1.3.0
  url_launcher: ^6.1.5 
  razorpay_flutter: ^1.3.7
  swipe_to: ^1.0.6
  google_sign_in: ^6.2.1
  uuid: ^4.0.0
  path: ^1.8.0
  image_picker_for_web: 2.2.0
  google_fonts:  ^6.2.1
  fl_chart: ^0.65.0
  quiver: ^3.0.0 
  




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  socket_io_client: ^3.0.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  provider: 6.1.2
  firebase_storage: ^12.4.4
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1
  iconsax: 0.0.8 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/image2.jpg
    - assets/images/logo.png
    - assets/images/mine1.jpg
    - assets/images/mine2.jpg
    - assets/images/her3.PNG
    - assets/images/HER4.PNG
    - assets/images/cup1.jpg
    - assets/images/we3.jpg
    - assets/images/plant1.png
    - assets/images/drinks.png
    - assets/images/dishes.png
    - assets/images/coffee1.jpg
    - assets/images/airtime.png
    - assets/images/curricullum.png
    - assets/images/community.png
    - assets/images/trends.jpg
    - assets/images/news.jpg
    - assets/images/beans.jpg
    - assets/images/cap1.jpg
    - assets/images/cap2.jpg
    - assets/images/cap3.jpg
    - assets/images/cap4.jpg
    - assets/images/cap5.jpg
    - assets/images/cap6.jpg
    - assets/images/cup7.jpg
    - assets/images/cup8.jpg
    - assets/images/cup9.jpg
    - assets/images/irish.jpg
    - assets/images/cool1.jpg
    - assets/images/cool.jpg
    - assets/images/e1.jpg
    - assets/images/e2.jpg
    - assets/images/e3.jpg
    - assets/images/e4.jpg
    - assets/images/e5.jpg
    - assets/images/e6.jpg
    - assets/images/e7.jpg
    - assets/images/e8.jpg
    - assets/images/e9.jpg
    - assets/images/e10.jpg
    - assets/images/f1.jpg
    - assets/images/f2.jpg
    - assets/images/f3.jpg
    - assets/images/f4.jpg
    - assets/images/f5.jpg
    - assets/images/f6.jpg
    - assets/images/f7.jpg
    - assets/images/f8.jpg
    - assets/images/f9.jpg
    - assets/images/d1.jpg
    - assets/images/d2.jpg
    - assets/images/de.jpg
    - assets/images/google.png






  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
