// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhw7vON2PHc_EIlj2j2wr6fhj4RVQadnw',
    appId: '1:285023635629:web:c13d8e2ea12151a63f9e24',
    messagingSenderId: '285023635629',
    projectId: 'barista-planet-658c1',
    authDomain: 'barista-planet-658c1.firebaseapp.com',
    storageBucket: 'barista-planet-658c1.firebasestorage.app',
    measurementId: 'G-D1QC835R7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApTx46KEbWd0w9IeVATkDbN7Z-OjDmABk',
    appId: '1:285023635629:android:265295e8cf19288e3f9e24',
    messagingSenderId: '285023635629',
    projectId: 'barista-planet-658c1',
    storageBucket: 'barista-planet-658c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAacLnRzSdu19AsdUkbG3H3seMznJWz52E',
    appId: '1:285023635629:ios:c640e0c170cc304a3f9e24',
    messagingSenderId: '285023635629',
    projectId: 'barista-planet-658c1',
    storageBucket: 'barista-planet-658c1.firebasestorage.app',
    iosBundleId: 'com.example.baristaPlanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAacLnRzSdu19AsdUkbG3H3seMznJWz52E',
    appId: '1:285023635629:ios:c640e0c170cc304a3f9e24',
    messagingSenderId: '285023635629',
    projectId: 'barista-planet-658c1',
    storageBucket: 'barista-planet-658c1.firebasestorage.app',
    iosBundleId: 'com.example.baristaPlanet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhw7vON2PHc_EIlj2j2wr6fhj4RVQadnw',
    appId: '1:285023635629:web:391b0ddbd145168b3f9e24',
    messagingSenderId: '285023635629',
    projectId: 'barista-planet-658c1',
    authDomain: 'barista-planet-658c1.firebaseapp.com',
    storageBucket: 'barista-planet-658c1.firebasestorage.app',
    measurementId: 'G-GE04RK5T71',
  );

}